version: '3'
services:
  nodejs:
    image: node:14
    container_name: my-node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: npm start